#ifndef LIBOCEANLIGHT_GLFW_ERR_CALLBACK_HPP_INCLUDED
#define LIBOCEANLIGHT_GLFW_ERR_CALLBACK_HPP_INCLUDED
#include <GLFW/glfw3.h>
void lol_glfw_error_callback(int, const char*);
#endif /* LIBOCEANLIGHT_GLFW_ERR_CALLBACK_HPP_INCLUDED */